// Downloads the latin + latin-ext subsets of the site typefaces and writes a
// self-hosted @font-face stylesheet. Run once; the results are committed.
import { mkdir, writeFile } from 'node:fs/promises';

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const OUT = new URL('../web/assets/fonts/', import.meta.url);

const families = [
  // The full axis set: Fraunces' SOFT and WONK are what make the display
  // sizes worth using, and they are only served if you ask for them by name.
  ['Fraunces',      'Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,300..900,0..100,0..1;1,9..144,300..900,0..100,0..1'],
  ['Newsreader',    'Newsreader:ital,opsz,wght@0,6..72,200..700;1,6..72,200..700'],
  ['IBM Plex Mono', 'IBM+Plex+Mono:wght@400;500;600'],
];

const KEEP = new Set(['latin', 'latin-ext']);

await mkdir(OUT, { recursive: true });
let css = '/* Self-hosted subsets. Generated by tools/fetch-fonts.mjs. */\n';
const seen = new Set();

for (const [name, spec] of families) {
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`;
  const sheet = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Google emits "/* subset */" comments before each @font-face block.
  const blocks = sheet.split('/*').slice(1);
  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim();
    if (!KEEP.has(subset)) continue;
    let block = '@font-face' + raw.slice(raw.indexOf('@font-face') + 10);
    block = block.slice(0, block.indexOf('}') + 1);

    const src = block.match(/url\((https:[^)]+)\)/)[1];
    const style = /font-style:\s*italic/.test(block) ? 'italic' : 'normal';
    const weight = block.match(/font-weight:\s*([^;]+);/)[1].trim().replace(/\s+/g, '-');
    const file = `${name.toLowerCase().replace(/\s+/g, '-')}-${subset}-${style}-${weight}.woff2`;
    if (seen.has(file)) continue;
    seen.add(file);

    const bytes = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(new URL(file, OUT), bytes);
    console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} kB`);

    css += block.replace(/url\(https:[^)]+\)/, `url(./${file})`) + '\n';
  }
}

await writeFile(new URL('fonts.css', OUT), css);
console.log('wrote web/assets/fonts/fonts.css');
